# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hugola"
license = "MIT"
licenselink = "https://github.com/gglanzani/hugola/blob/master/LICENSE.md"
description = "A simple hugo theme derived from purecss.io"
homepage = "http://github.com/gglanzani/hugola"
tags = ["purecss"]
features = ["", ""]
min_version = 0.14

[author]
  name = "Giovanni Lanzani"
  homepage = "http://lanzani.nl"

